service: hendersonRecyclingScheduleReader

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getschedule:
    handler: handler.getschedule

package:
  excludeDevDependencies: false

resources:
  Resources:
    hendersonRecyclingSchedule:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hendersonRecyclingSchedule
        AttributeDefinitions:
          - AttributeName: scheduleId
            AttributeType: S
        KeySchema:
          - AttributeName: scheduleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    DynamoDBIamPolicy: 
      Type: AWS::IAM::Policy
      DependsOn: hendersonRecyclingSchedule
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource: arn:aws:dynamodb:*:*:table/hendersonRecyclingSchedule
        Roles:
          - Ref: IamRoleLambdaExecution